import { Geist, Geist_Mono } from "next/font/google";
import "./style.css";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Brentford Cab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <link rel="icon" type="image/x-icon" href="/images//favicon.ico" />

      <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images//apple-touch-icon-114x114-precomposed.png" />

      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images//apple-touch-icon-72x72-precomposed.png" />

      <link rel="apple-touch-icon-precomposed" href="/images//apple-touch-icon-57x57-precomposed.png" />

      <link rel="stylesheet" type="text/css" href="/libraries/loader/loaders.min.css" />

      <link
        href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic'
        rel='stylesheet' type='text/css' />
      <link href='https://fonts.googleapis.com/css?family=Cabin:400,400italic,500,500italic,600,600italic,700,700italic'
        rel='stylesheet' type='text/css' />
      <link href='https://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css' />
      <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css' />
      <link
        href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic'
        rel='stylesheet' type='text/css' />
      <link
        href='https://fonts.googleapis.com/css?family=Lato:400,100italic,100,300,300italic,400italic,700,700italic,900,900italic'
        rel='stylesheet' type='text/css' />

      <link rel="stylesheet" type="text/css" href="/libraries/bootstrap/bootstrap.min.css" />
      <link rel="stylesheet" type="text/css" href="/libraries/bootstrap/bootstrap-datetimepicker.min.css" />

      <link rel="stylesheet" type="text/css" href="/libraries/fonts/font-awesome.min.css" />

      <link rel="stylesheet" type="text/css" href="/libraries/owl-carousel/owl.carousel.css" />
      <link rel="stylesheet" type="text/css" href="/libraries/owl-carousel/owl.theme.css" />

      <link rel="stylesheet" type="text/css" href="/libraries/flexslider/flexslider.css" />

      <link rel="stylesheet" type="text/css" href="/libraries/animate/animate.min.css" />

      <link rel="stylesheet" type="text/css" href="/css/plugins.css" />
      <link rel="stylesheet" type="text/css" href="/css/navigation-menu.css" />


      <link rel="stylesheet" type="text/css" href="/style.css" />
      <link rel="stylesheet" type="text/css" href="/css/shortcodes.css" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="main-container">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
